Add MAYZ circulating supply
minswap/market-cap pull request #128
Opened 2023-09-22 17:07 UTC by TheTapHouse

Output produces 3,636,363 circulating supply (0.36%)

2023-09-22 17:25 UTC, avilsmeier commented
Output is correct, thank you guys!

2023-09-24 18:00 UTC, avilsmeier requested changes
Please, add "stake1uxhx6z2s9dpmss9e7ks0l065kmd22uwgjzdgl78ygwvl25gm9l8gm" to treasuryRaw.

2023-09-25 15:40 UTC, longngn approved these changes

2023-09-25 15:42 UTC, longngn commented
merged via https://github.com/minswap/market-cap/pull/131

2023-09-25 15:42 UTC, closed without merging